baseURL = 'https://linborui.github.io/'

defaultContentLanguageInSubdir = true

[module]
  [[module.imports]]
    path = "github.com/hugo-toha/toha/v4"
  [[module.mounts]]
    source = "static/files"
    target = "static/files"
  [[module.mounts]]
    source = "./node_modules/flag-icon-css/flags"
    target = "static/flags"
  [[module.mounts]]
    source = "./node_modules/@fontsource/mulish/files"
    target = "static/files"
  [[module.mounts]]
    source = "./node_modules/katex/dist/fonts"
    target = "static/fonts"

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
  [languages.zh-tw]
    contentDir = 'content/zh-tw'
    disabled = false
    languageCode = 'zh-TW'
    languageDirection = 'ltr'
    languageName = '繁體中文'
    weight = 2


[Params]

  background = 'images/background.jpg'

  [Params.features]
    [Params.features.darkMode]
      enable = true

    [Params.features.blog]
      enable = false

    [Params.features.notes]
      enable = false
  
  [Params.footer]
    [Params.footer.newsletter]
      enable = false
