baseURL = "https://linborui.github.io/"

defaultContentLanguageInSubdir = true

[module]
  [[module.imports]]
    path = "github.com/hugo-toha/toha/v4"
  [[module.mounts]]
    source = "static/files"
    target = "static/files"
  [[module.mounts]]
    source = "./node_modules/flag-icon/flags"
    target = "static/flags"
  [[module.mounts]]
    source = "./node_modules/@fontsource/mulish/files"
    target = "static/files"
  [[module.mounts]]
    source = "./node_modules/katex/dist/fonts"
    target = "static/fonts"

[languages]
  [languages.en]
    contentDir = "content/en"
    disabled = false
    languageCode = "en-US"
    languageDirection = "ltr"
    languageName = "English"
    weight = 1
    title = "Bo-Rui's Personal Website"
  [languages.zh-tw]
    contentDir = "content/zh-tw"
    disabled = false
    languageCode = "zh-tw"
    languageDirection = "ltr"
    languageName = "繁體中文"
    weight = 2
    title = "柏叡の個人網站"


[params]

  background = "images/site/background.jpg"

  [params.logo]
    favicon = "images/site/favicon.png"

  [params.features]
    [params.features.darkMode]
      enable = true

    [params.features.blog]
      enable = false

    [params.features.notes]
      enable = false

    [params.features.flags]
      enable = true
  
  [params.footer]
    enable = true

    [params.footer.newsletter]
      enable = false
